
on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    ## depth 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      ## Set new version#121jlö
      - name: Bump version and create tag
        id: semanticversion
        uses: hennejg/github-tag-action@v4.2.4
        with:
          release_branches: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix : 'maint-'

      - name: Verify and print new build number
        run: |
          if echo '${{ steps.semanticversion.outputs.new_tag }}' |grep -Eq '^maint-[0-9]+[.][0-9]+[.][0-9]+$'; then
            echo Tag '${{ steps.semanticversion.outputs.new_tag }}', New version '${{ steps.semanticversion.outputs.new_version }}', Changelog '${{ steps.semanticversion.outputs.changelog }}'
          else
            echo 'unexpected tag format - aborting'
            exit -1
          fi

      - name: Set version variable
        run: |
          echo "NEW_VERSION=${{ steps.semanticversion.outputs.new_version }}" >> $GITHUB_ENV
